### ISSUE TITLE
[documents] update ER diagram

### ISSUE THREAD

**Issue by vantheav** [pnc-virtual-company/2021-G2-VC2-PART2#22]
update relationship for this week

**Comment by vichekalo** [comment]
[ER-DIAGRAM.pptx](https://github.com/pnc-virtual-company/2021-G2-VC2-PART2/files/7772253/ER-DIAGRAM.pptx)

**Comment by vichekalo** [comment]
[ER-DIAGRAM.pptx](https://github.com/pnc-virtual-company/2021-G2-VC2-PART2/files/7772260/ER-DIAGRAM.pptx)
