### ISSUE TITLE
[Sign_In] Crude users

### ISSUE THREAD

**Issue by vichekalo** [pnc-virtual-company/2021-G2-VC2-PART2#4]
Crude users ( Get/Post/Update/Destroy) create , edit and delete user.

**Comment by lydenchai** [comment]
Here is the information of user admin 
-Username: Administrator
-Password: Admin@2021!@#$
-Token: 2|W8Bgx8k7g5NJVGXTQr2FFl2Ng8K7tMbw3bqONdpX
=====================================================
{
  "Message": "Created",
  "data": {
    "username": "Administrator",
    "email": "admin@gmail.com",
    "role": "Admin",
    "image": "ruuxEw5Ma3s2HeimJuln2obGP8F86Svcj9ErafNs.jpg",
    "updated_at": "2021-12-17T04:27:33.000000Z",
    "created_at": "2021-12-17T04:27:33.000000Z",
    "id": 2
  },
  "token": "2|W8Bgx8k7g5NJVGXTQr2FFl2Ng8K7tMbw3bqONdpX"
}
